components:
  schemas:
    image:
      additionalProperties: false
      description: Information about the update image
      properties:
        checksum:
          description: The SHA-256 checksum of the update image
          type: string
        id:
          description: A unique identifier for the image
          readOnly: true
          type: integer
        progress:
          description: The progress of the current upload/fetch operation
          type: number
        state:
          description: The state of the update image
          enum:
          - UPLOADING
          - VALIDATING
          - UPLOAD_ERROR
          - VALID
          - INVALID
          type: string
        state_description:
          description: A more detailed description of the state
          type: string
        version:
          description: The version of the update image
          type: string
      required:
      - state
      - state_description
      type: object
    images:
      additionalProperties: false
      description: List of update images
      properties:
        items:
          description: An array containing the available update images
          items:
            $ref: '#/components/schemas/image'
          type: array
      type: object
    update:
      additionalProperties: false
      description: The overall status of the update
      properties:
        last_state_time:
          description: 'The time of the last state transition, in Unix epoch seconds

            '
          type: integer
        state:
          description: The state of the update
          enum:
          - IDLE
          - INITIALIZING
          - INITIALIZED
          - RUNNING
          - FAILED_GRACEFUL
          - FAILED_CRITICAL
          type: string
        state_description:
          description: A more detailed description of the state
          type: string
        target_version:
          description: The version the system will be updated to
          type: string
        update_history:
          description: A list of past updates. The first element of the list is an
            installation
          items:
            additionalProperties: false
            description: Information about a previous update
            properties:
              time:
                description: 'The time of the update, in Unix epoch seconds

                  '
                type: integer
              version:
                description: The version that was installed
                type: string
            type: object
          type: array
      required:
      - state
      - state_description
      - last_state_time
      - update_history
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: Access token approach to reaching appliance
      scheme: bearer
      type: http
    oAuth2NoScopes:
      description: Credential approach to retrieving token
      flows:
        clientCredentials:
          refreshUrl: /mgmt.aaa/1.0/token
          scopes: {}
          tokenUrl: /mgmt.aaa/1.0/token
      type: oauth2
info:
  description: Service that handles software updates
  title: Software Update Service
  version: '2.0'
openapi: 3.0.2
paths:
  /npm.system_update/2.0/images:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/images'
                type: array
          description: ''
      summary: get
      tags:
      - images
  /npm.system_update/2.0/images/fetch:
    post:
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              description: Fetch parameters
              properties:
                url:
                  description: The url where to fetch the update image from
                  type: string
              required:
              - url
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/image'
                type: array
          description: ''
      summary: fetch
      tags:
      - images
  /npm.system_update/2.0/images/items/{id}:
    delete:
      parameters:
      - description: A unique identifier for the image
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: On success, the server does not provide any body in the response.
      summary: delete
      tags:
      - images
    get:
      parameters:
      - description: A unique identifier for the image
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/image'
                type: array
          description: ''
      summary: get
      tags:
      - images
  /npm.system_update/2.0/images/upload:
    post:
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              description: The update image binary
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/image'
                type: array
          description: ''
      summary: upload
      tags:
      - images
  /npm.system_update/2.0/update:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/update'
                type: array
          description: ''
      summary: get
      tags:
      - update
  /npm.system_update/2.0/update/init:
    post:
      responses:
        '200':
          description: On success, the server does not provide any body in the response.
      summary: init
      tags:
      - update
  /npm.system_update/2.0/update/reset:
    post:
      responses:
        '200':
          description: On success, the server does not provide any body in the response.
      summary: reset
      tags:
      - update
  /npm.system_update/2.0/update/start:
    post:
      responses:
        '200':
          description: On success, the server does not provide any body in the response.
      summary: start
      tags:
      - update
security:
- oAuth2NoScopes: []
- bearerAuth: []
servers:
- description: Example API base path for URL
  url: https://{URL}:{Port}/api/
  variables:
    Port:
      default: '443'
      enum:
      - '443'
    URL:
      default: abc.example.com
