components:
  schemas:
    status:
      additionalProperties: false
      description: OpenSSL FIPS configuration
      properties:
        enabled_current: {description: 'Whether the system is currently running in
            FIPS mode

            ', readOnly: true, type: boolean}
        enabled_next_boot: {description: 'Whether the system will run in FIPS mode
            on the next boot

            ', type: boolean}
      required: [enabled_next_boot]
      type: object
  securitySchemes:
    bearerAuth: {bearerFormat: JWT, description: Access token approach to reaching
        appliance, scheme: bearer, type: http}
    oAuth2NoScopes:
      description: Credential approach to retrieving token
      flows:
        clientCredentials:
          refreshUrl: /mgmt.aaa/1.0/token
          scopes: {}
          tokenUrl: /mgmt.aaa/1.0/token
      type: oauth2
info: {description: Configure OpenSSL FIPS mode, title: FIPS configuration, version: '1.0'}
openapi: 3.0.2
paths:
  /npm.fips/1.0/status:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {$ref: '#/components/schemas/status'}
                type: array
          description: ''
      summary: get
      tags: [status]
    put:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                items:
                  items: {$ref: '#/components/schemas/status'}
                  type: array
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {$ref: '#/components/schemas/status'}
                type: array
          description: ''
      summary: set
      tags: [status]
security:
- oAuth2NoScopes: []
- bearerAuth: []
servers:
- description: Example API base path for URL
  url: https://{URL}:{Port}/api/
  variables:
    Port:
      default: '443'
      enum: ['443']
    URL: {default: abc.example.com}
