components:
  schemas:
    async_error_metrics_list:
      additionalProperties: false
      description: Individual error key/value.
      properties:
        key:
          description: Error metric ID.
          type: string
        value:
          description: Error metric value.
          type: string
      required:
      - key
      - value
      type: object
    export:
      additionalProperties: true
      description: Configuration, status and statistics of an export.
      properties:
        config:
          additionalProperties: false
          description: Configuration of an export.
          properties:
            connection_timeout_msec:
              default: 180000
              description: Max period of time for which the handle waits for a user
                action (e.g starts to download the packets, set PREPARE mode, etc).
              type: integer
            end_time:
              description: Time (seconds from epoch) at which export is to end.
              type: string
            filters:
              additionalProperties: false
              description: Collection of filter criteria.
              properties:
                items:
                  $ref: '#/components/schemas/filters_list'
              type: object
            handle_timeout_msec:
              description: Period of time for which the export handle is available
                after the packets download is terminated.
              type: integer
            mode:
              description: Export mode.
              enum:
              - LIVE_STREAM
              - BUFFER_STREAM
              - STREAM_TO_FILE
              - LEGACY
              - PREPARE
              type: string
            output_filename:
              description: If sending packets to file, the filename within the probe
                file system.
              type: string
            output_format:
              description: Output format type.
              enum:
              - PCAP_US
              - PCAP_NS
              - PCAPNG_US
              - PCAPNG_NS
              type: string
            path:
              description: Path of the source to open.
              type: string
            snap_length:
              default: 65535
              description: Packet snap length for this export.
              type: integer
            start_time:
              description: Time (seconds from epoch) at which export is to begin.
              type: string
            stop_rule:
              additionalProperties: false
              description: Stop rule for an export.
              properties:
                packet_limit:
                  description: Max number of packets.
                  type: integer
                size_limit:
                  description: Max bytes of packet data.
                  type: integer
                time_limit:
                  description: Max time in seconds.
                  type: integer
              type: object
            time_intervals:
              description: Array of time intervals.
              items:
                $ref: '#/components/schemas/time_interval_t'
              type: array
          required:
          - path
          type: object
        id:
          description: Export unique identifier.
          readOnly: true
          type: string
        status:
          additionalProperties: false
          description: Status of an export.
          properties:
            creation_time:
              description: Time at which the export was created.
              readOnly: true
              type: string
            error:
              additionalProperties: false
              description: Asynchronous task error object.
              properties:
                error_id:
                  description: Error code.
                  type: string
                error_metrics:
                  $ref: '#/components/schemas/async_error_metrics_list'
                error_text:
                  description: Error text.
                  type: string
              required:
              - error_id
              - error_text
              type: object
            owner:
              description: User who initiated the export.
              readOnly: true
              type: string
            progress:
              description: Processing progress including both filtering and buffering/streaming.
              readOnly: true
              type: number
            state:
              description: Export state.
              enum:
              - UNINITIALIZED
              - INITIALIZING
              - READY
              - RUNNING
              - STREAMING
              - ERRORS
              - NODATA
              - DONE
              type: string
            stats:
              additionalProperties: false
              description: Statistics of an export.
              properties:
                dropped_packets:
                  description: Number of dropped packets.
                  readOnly: true
                  type: integer
                estimated_bytes:
                  description: Estimated number of bytes that will be exported.
                  readOnly: true
                  type: integer
                estimated_packets:
                  description: Estimated number of packets that will be exported.
                  readOnly: true
                  type: integer
                exported_bytes:
                  description: Number of exported bytes.
                  readOnly: true
                  type: integer
                exported_packets:
                  description: Number of exported packets.
                  readOnly: true
                  type: integer
                processed_packets:
                  description: Number of processed packets.
                  readOnly: true
                  type: integer
                total_bytes:
                  description: Approximate number of bytes in the input.
                  readOnly: true
                  type: integer
                truncated:
                  description: True in case the output has been truncated.
                  type: boolean
              type: object
          type: object
      type: object
    exports:
      additionalProperties: false
      description: Collection of exports on the device.
      properties:
        items:
          description: Array of exports.
          items:
            $ref: '#/components/schemas/export'
          type: array
      type: object
    filters_list:
      additionalProperties: false
      description: Filter
      properties:
        context:
          description: Context from which the filter was applied (e.g., user request,
            data drill-down, etc).
          enum:
          - NONE
          - INTERNAL
          - USER
          - DRILL_DOWN
          type: string
        id:
          description: Filter criterion ID.
          type: string
        type:
          description: The type of filter used on the data.
          enum:
          - BPF
          - STEELFILTER
          - WIRESHARK
          type: string
        value:
          description: Query filter text to use.
          type: string
      required:
      - id
      - type
      - value
      type: object
    time_interval_t:
      additionalProperties: false
      description: Time interval.
      properties:
        end_time:
          description: Time (seconds from epoch) at which the interval ends.
          type: string
        start_time:
          description: Time (seconds from epoch) at which the interval begins.
          type: string
      required:
      - start_time
      - end_time
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: Access token approach to reaching appliance
      scheme: bearer
      type: http
    oAuth2NoScopes:
      description: Credential approach to retrieving token
      flows:
        clientCredentials:
          refreshUrl: /mgmt.aaa/1.0/token
          scopes: {}
          tokenUrl: /mgmt.aaa/1.0/token
      type: oauth2
info:
  description: Packet export API
  title: Packet Export API
  version: '1.3'
openapi: 3.0.2
paths:
  /npm.packet_export/1.3/exports:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                items:
                  items:
                    $ref: '#/components/schemas/export'
                  type: array
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/export'
                type: array
          description: ''
      summary: create
      tags:
      - exports
  /npm.packet_export/1.3/exports/items/{+id}:
    delete:
      parameters:
      - description: ''
        in: path
        name: +id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: On success, the server does not provide any body in the response.
      summary: delete
      tags:
      - exports
    get:
      parameters:
      - description: ''
        in: path
        name: +id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/export'
                type: array
          description: ''
      summary: get
      tags:
      - exports
    put:
      parameters:
      - description: ''
        in: path
        name: +id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                items:
                  items:
                    $ref: '#/components/schemas/export'
                  type: array
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/export'
                type: array
          description: ''
      summary: set
      tags:
      - exports
  /npm.packet_export/1.3/exports{?path}:
    get:
      parameters:
      - description: ''
        in: query
        name: path
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/exports'
                type: array
          description: ''
      summary: get
      tags:
      - exports
  /npm.packet_export/1.3/packets/items/{+id}:
    get:
      parameters:
      - description: ''
        in: path
        name: +id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: On success, the server does not provide any body in the response.
      summary: packets
      tags:
      - exports
security:
- oAuth2NoScopes: []
- bearerAuth: []
servers:
- description: Example API base path for URL
  url: https://{URL}:{Port}/api/
  variables:
    Port:
      default: '443'
      enum:
      - '443'
    URL:
      default: abc.example.com
